"""Generate the committed monthly review pack (markdown).

Usage:  python reports/build_review_pack.py [YYYY-MM]

Reads data/generated/verdicts.csv (run classify.py for the month first) and, if
a previous month exists in data/generated/verdict_history/, diffs the verdicts
to show movers. Output: reports/packs/review_<month>.md - the artifact for the
monthly portfolio meeting.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from pipeline.common import (  # noqa: E402
    COUNTRY_VERDICTS_PATH,
    HISTORY_DIR,
    NO_DATA,
    VERDICT_ORDER,
    VERDICTS_PATH,
)

PACKS_DIR = Path(__file__).resolve().parent / "packs"


def eur(x) -> str:
    if pd.isna(x):
        return "—"
    if abs(x) >= 1e6:
        return f"€{x/1e6:,.2f}m"
    return f"€{x:,.0f}"


def table(df: pd.DataFrame, cols: dict[str, str], n: int = 10) -> str:
    if df.empty:
        return "_none_\n"
    lines = ["| " + " | ".join(cols.values()) + " |",
             "|" + "---|" * len(cols)]
    for _, r in df.head(n).iterrows():
        cells = []
        for key in cols:
            val = r[key]
            if key in ("net_sales_ttm", "net_sales_l6m", "cm3_l6m"):
                val = eur(val)
            elif key in ("cm3_pct_l6m", "cm3_target", "sales_trend_pct"):
                val = "—" if pd.isna(val) else f"{val:.1f}"
            elif key == "product":
                val = str(val)[:55]
            cells.append(str(val))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def main(month: str | None = None) -> Path:
    v = pd.read_csv(VERDICTS_PATH)
    month = month or v["review_month"].iloc[0]
    if v["review_month"].iloc[0] != month:
        hist = HISTORY_DIR / f"verdicts_{month}.csv"
        if not hist.exists():
            raise SystemExit(f"No verdicts for {month} - run pipeline/classify.py {month}")
        v = pd.read_csv(hist)

    prev_month = str(pd.Period(month) - 1)
    prev_path = HISTORY_DIR / f"verdicts_{prev_month}.csv"
    prev = pd.read_csv(prev_path) if prev_path.exists() else None

    parts: list[str] = []
    parts.append(f"# Vanatari Portfolio Review — {month}\n")
    parts.append(
        "Generated by `reports/build_review_pack.py`. Rules: `config/rules.yaml` · "
        "targets: AP26 sales-weighted per SKU × channel (`config/ap26_targets.json`) · "
        "headline unit: SKU × channel (per-country detail in the app's *By country* tab).\n"
    )
    country = pd.read_csv(COUNTRY_VERDICTS_PATH) if COUNTRY_VERDICTS_PATH.exists() else None

    # ---- headline ----
    ns = v["net_sales_l6m"].sum()
    cm3 = v["cm3_l6m"].sum()
    cm3_pct = cm3 / ns * 100 if ns else float("nan")
    target = (v["cm3_target"] * v["net_sales_l6m"]).sum() / ns if ns else float("nan")
    parts.append("## Headline\n")
    parts.append(
        f"- Net sales TTM: **{eur(v['net_sales_ttm'].sum())}** · last 6m: {eur(ns)}\n"
        f"- CM3 last 6m: **{eur(cm3)}** = **{cm3_pct:.1f}%** vs plan "
        f"{target:.1f}% (**{cm3_pct - target:+.1f}pp**)\n"
        f"- {len(v):,} SKU × channels reviewed; "
        f"{int(v['verdict'].isin(['Fix', 'Exit']).sum())} need action (Fix/Exit)"
        + (f" · {len(country):,} SKU × markets underneath\n" if country is not None else "\n")
    )

    # ---- verdict distribution ----
    parts.append("## Verdicts\n")
    agg = (
        v.groupby("verdict")
        .agg(n=("sku", "count"), sales=("net_sales_ttm", "sum"), cm3=("cm3_l6m", "sum"))
        .reindex([x for x in VERDICT_ORDER + [NO_DATA] if x in v["verdict"].values])
    )
    lines = ["| Verdict | SKU × channels | Net sales TTM | CM3 last 6m |", "|---|---|---|---|"]
    for name, r in agg.iterrows():
        lines.append(f"| {name} | {int(r['n'])} | {eur(r['sales'])} | {eur(r['cm3'])} |")
    parts.append("\n".join(lines) + "\n")

    # ---- movers vs previous month ----
    parts.append(f"## Verdict changes vs {prev_month}\n")
    if prev is None:
        parts.append(
            "_First tracked month - no previous verdict file in "
            "`data/generated/verdict_history/`. Changes appear from next month on._\n"
        )
    else:
        keys = ["brand", "channel", "sku"]
        merged = v.merge(
            prev[keys + ["verdict"]].rename(columns={"verdict": "verdict_prev"}),
            on=keys, how="left",
        )
        changed = merged[
            merged["verdict_prev"].notna() & (merged["verdict"] != merged["verdict_prev"])
        ].sort_values("net_sales_ttm", ascending=False)
        changed = changed.assign(
            change=changed["verdict_prev"] + " → " + changed["verdict"]
        )
        parts.append(table(
            changed,
            {"sku": "SKU", "channel": "Channel", "product": "Product",
             "change": "Change", "net_sales_ttm": "Net TTM", "reasons": "Why"},
            n=20,
        ))

    # ---- biggest items per action bucket ----
    for verdict, blurb in [
        ("Exit", "delist / liquidate in this market"),
        ("Fix", "margin repair: price, fees, COGS, ad efficiency"),
        ("Scale", "feed with budget, inventory, expansion"),
        ("Harvest", "milk: cut ad support, no aggressive restock"),
    ]:
        sub = v[v["verdict"] == verdict].sort_values("net_sales_ttm", ascending=False)
        parts.append(f"## {verdict} — {blurb} ({len(sub)})\n")
        parts.append(table(
            sub,
            {"sku": "SKU", "channel": "Channel", "product": "Product",
             "net_sales_ttm": "Net TTM", "cm3_pct_l6m": "CM3%",
             "cm3_target": "Plan", "reasons": "Why"},
        ))

    # ---- data gaps ----
    nodata = v[v["verdict"] == "No data"]
    est = v[v["cm_source"].astype(str).str.startswith("estimated")]
    censored_n = (
        int(country["censored"].fillna(False).sum()) if country is not None else 0
    )
    parts.append("## Data gaps to close\n")
    parts.append(
        f"- **{len(nodata)}** SKU × channels unclassifiable "
        f"({eur(nodata['net_sales_ttm'].sum())} TTM): Jasnum has no margin feed, "
        "the wowtamins webshop is not connected, long tail under 3 months of data.\n"
        f"- **{len(est)}** webshop rows run on ESTIMATED margins "
        "(`config/shopify_assumptions.yaml` placeholders; webshop CM3 subtracts "
        "actual Google Ads spend via Windsor.ai only where it exists; Meta/other "
        "channels not connected).\n"
        f"- **{censored_n}** SKU × markets have censored launch "
        "dates (product already sold in Jul 2024). Fix in "
        "`data/overrides/launch_dates_overrides.csv`.\n"
        "- wowtamins Amazon: no PPC data (CM2 = CM3), June 2025 missing, and an "
        "account-wide supply collapse since May 2026 "
        "(see `docs/wowtamins_stockout_2026-07.md`).\n"
    )

    PACKS_DIR.mkdir(parents=True, exist_ok=True)
    out = PACKS_DIR / f"review_{month}.md"
    out.write_text("\n".join(parts))
    print(f"-> {out}")
    return out


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
